name: zalo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.15.2
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.7.0
  firebase_storage: ^12.1.0

  # Ảnh
  image_picker: ^1.1.2

  supabase_flutter: ^2.3.3

  # Khác
  rxdart: ^0.28.0
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  timeago: ^3.3.0

  # ⭐ Font Awesome (icon Instagram-style)
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

# ⭐ flutter_icons phải nằm ngoài dev_dependencies
flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/avatar_app.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
