name: zalo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  firebase_storage: ^13.0.4

  # Ảnh
  image_picker: ^1.1.2

  # Thêm Supabase (⭐ quan trọng)
  supabase_flutter: ^2.12.0

  # Khác
  rxdart: ^0.28.0
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  timeago: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

# ⭐ flutter_icons phải nằm ngoài dev_dependencies
flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/avatar_app.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
